/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sopa;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import javafx.scene.layout.Border;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import scanner.Token;

/**
 *
 * @author josue
 */
public class Sopa extends javax.swing.JFrame {

    /**
     * Creates new form Sopa
     */
    GridLayout gridSopa;
    int row, column;
    public ArrayList<Container> Positions;
    

    public Sopa(int row, int column) {
        this.row = row;
        this.column = column;

        initComponents();
        gridSopa = new GridLayout(row + 1, column + 1);
        System.out.println("columna " + column);
        System.out.println("row " + row);
        Positions = new ArrayList<Container>();
        Container container;

        javax.swing.border.Border border = BorderFactory.createLineBorder(Color.black, 1);

        for (int i = 0; i < row + 1; i++) {
            for (int j = 0; j < column + 1; j++) {

                if (j == 0) {
                    container = new Container(i,j,"" + i, JLabel.CENTER);
                    //container = new Container();
                    container.setText("" + i);
                    container.setSize(25, 25);
                    container.setOpaque(true);
                    container.setBackground(Color.red);
                    container.setForeground(Color.white);
                    container.setBorder(border);
                    container.setVisible(true);
                    this.add(container);
                } else if (i == 0) {
                    container = new Container(i,j,"" + j, JLabel.CENTER);
                    //container = new JLabel("" + j, JLabel.CENTER);
                    container.setSize(25, 25);
                    container.setOpaque(true);
                    container.setBackground(Color.red);
                    container.setForeground(Color.white);
                    container.setBorder(border);
                    container.setVisible(true);
                    this.add(container);
                } else {
                    container = new Container(i,j,"A", JLabel.CENTER);
                    container.setSize(25, 25);
                    container.setOpaque(true);
                    container.setBackground(Color.white);
                    container.setForeground(Color.black);
                    container.setBorder(border);
                    container.setVisible(true);
                    this.add(container);
                    Positions.add(container);
                }
                

            }
        }
        this.setLayout(gridSopa);
        this.setSize(300, 300);
        this.setVisible(true);
    }

    public void cargarSopa() {
        JLabel letra;
        for (int i = 0; i >= row; i++) {
            for (int j = 0; j >= column; j++) {
                letra = new JLabel("A");
                letra.setSize(25, 25);
                letra.setVisible(true);
                this.add(letra);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Sopa(7,8).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
